---
collections:
  - name: ansible.posix
  - name: community.vmware
    version: 1.13.0
  - name: community.general
    version: 3.5.0
  - name: https://github.com/rthdev/ansible-collections.git
    type: git
    version: develop

